# -*- coding: utf-8 -*-
"""Sentiment Andrea

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QNfSWk12RssXRS2fAy-ddp-8hMp4KFqK
"""

pip install transformers torch sentencepiece

pip install transformers torch

import pandas as pd
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline

MODEL_NAME = "nlptown/bert-base-multilingual-uncased-sentiment"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME)

sentiment_pipeline = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

file_path = "/content/sample_data/rom1.csv"  # Assicurati che il percorso sia corretto
with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

data = []

#sentiment analysis su ogni riga
for line in lines:
    testo = line.strip()
    if testo:
        result = sentiment_pipeline(testo)
        label = result[0]['label']
        score = result[0]['score']
        data.append([testo, label, score])

#Creare un DataFrame con i risultati
df = pd.DataFrame(data, columns=["Testo", "Sentiment", "Score"])

output_file = "sentiment_analysis.xlsx"
df.to_excel(output_file, index=False)

print(f"✅ Sentiment Analysis completata! File salvato come: {output_file}")